#!/usr/bin/env bash

echo "[info] replace git dotfile"
for dotname in config ignore attributes; do
    dotfile="${HOME}/.git${dotname}"
    [[ -e "${dotfile}" ]] && rm -rf "${dotfile}"
done

ln -sfv "$(__dir__)" "$(xdg_config_home)"
touch "$(__dir__)"/local
