#!/usr/bin/env bash

echo "[info] check prerequisites"
if [[ "$OSTYPE" == "darwin"* ]]; then
    if command -v git &> /dev/null; then
        echo "[info] git found, ok"
    else
        echo 1>&2 "[error] git not found, ng"
        exit
    fi
else
    echo 1>&2 "[error] unsupported os-type"
    exit
fi

# backup dotfile
DOTFILE_SOURCE="${HOME}"/.dotfile
DOTFILE_BACKUP="${HOME}"/.dotfile.bak

if [[ -e "${DOTFILE_BACKUP}" ]]; then
    echo "[info] clear old ${DOTFILE_BACKUP}"
    rm -rf "${DOTFILE_BACKUP}"
fi

mkdir "${DOTFILE_BACKUP}"

if [[ -e "${DOTFILE_SOURCE}" ]]; then
    echo "[info] store previous dotfile ${DOTFILE_SOURCE} into ${DOTFILE_BACKUP}"
    mv "${DOTFILE_SOURCE}" "${DOTFILE_BACKUP}"
fi

echo "[info] get dotfile source"
git clone \
    --depth 1 \
    https://github.com/yhue/peaberry.git \
    "${DOTFILE_SOURCE}" \
    ;

(
    export DOTFILE_SOURCE
    export DOTFILE_BACKUP

    cd "${DOTFILE_SOURCE}"

    echo "[info] start dotfile installation"
    . ./install
)

echo "[info] finish bootstrap"
