#!/usr/bin/env bash

function cmd_test() {
    if command -v ${1} &> /dev/null; then
        echo "[info] ${1} found, ok"
    else
        echo 1>&2 "[error] ${1} not found, ng"
        exit
    fi
}

echo "[info] check prerequisites"
if [[ "$OSTYPE" == "darwin"* ]]; then
    cmd_test curl
    cmd_test tar
else
    echo 1>&2 "[error] unsupported os-type"
    exit
fi

# backup dotfile
DOTFILE_SOURCE="${HOME}"/.dotfile
DOTFILE_BACKUP="${HOME}"/.dotfile.bak

if [[ -e "${DOTFILE_BACKUP}" ]]; then
    echo "[info] clear old ${DOTFILE_BACKUP}"
    rm -rf "${DOTFILE_BACKUP}"
fi

mkdir "${DOTFILE_BACKUP}"

if [[ -e "${DOTFILE_SOURCE}" ]]; then
    echo "[info] store previous dotfile ${DOTFILE_SOURCE} into ${DOTFILE_BACKUP}"
    mv "${DOTFILE_SOURCE}" "${DOTFILE_BACKUP}"
fi

mkdir "${DOTFILE_SOURCE}"

echo "[info] get dotfile source"
curl -fsSL https://github.com/yhue/peaberry/archive/refs/heads/main.tar.gz |
    tar zxf - --directory="${DOTFILE_SOURCE}" --strip-components 1 \
    ;

(
    export DOTFILE_SOURCE
    export DOTFILE_BACKUP

    cd "${DOTFILE_SOURCE}" || exit

    echo "[info] start dotfile installation"
    . ./install
)

echo "[info] finish bootstrap"
echo "[recommend] restart computers to cleanly activate all features"
