#!/usr/bin/env bash

echo "[info] check prerequisites"
if [[ "$OSTYPE" == "darwin"* ]]; then
    if command -v git &> /dev/null; then
        echo "[info] git found, ok"
    else
        echo 1>&2 "[error] git not found, ng"
        exit
    fi
else
    echo 1>&2 "[error] unsupported os-type"
    exit
fi

src=${HOME}/.dotfile
bak=${HOME}/.dotfile.bak

if [[ -e ${bak} ]]; then
    echo "[info] clear old ${bak}"
    rm -rf ${bak}
fi

if [[ -f ${src} ]]; then
    echo "[info] store a file ${src} into ${bak}"
    mkdir ${bak}
    mv ${src} ${bak}
elif [[ -d ${src} ]]; then
    echo "[info] store a directory ${src} as ${bak}"
    mv ${src} ${bak}
fi

echo "[info] get dotfile source"
git clone \
    --depth 1 \
    https://github.com/yhue/peaberry.git \
    ${src} \
    ;

(
    echo "[info] start dotfile installation"
    cd ${src}
    ./install
)

echo "[info] finish bootstrap"
