#!/usr/bin/env bash

. bash/util
. bash/dotfile_util

# transaction
function tx() {
    {
        echo "[info] transaction ${1}"
        . ${1}
    } || {
        echo >&2 "[error] ${1} failed"
        exit 1
    }
}

# prepare xdg spec
[[ -d "$(xdg_config_home)" ]] || mkdir -p "$(xdg_config_home)"

if [[ "$OSTYPE" == "darwin"* ]]; then
    tx os/darwin/bootstrap
    tx homebrew/bootstrap
    tx bash/bootstrap
    tx vim/bootstrap
    tx git/bootstrap
    tx os/darwin/postamble
else
    echo >&2 "[error] unsupported os-type"
    exit 2
fi
