#!/usr/bin/env bash

. bash/util

# transaction
function tx() {
    . ${1} || {
        echo 1>&2 "[error] ${1} failed"
        exit
    }
}

if [[ "$OSTYPE" == "darwin"* ]]; then
    #tx os/darwin/bootstrap
    #tx homebrew/bootstrap
    #tx os/darwin/postamble
else
    echo 1>&2 "[error] unsupported os-type"
    exit
fi
