#!/usr/bin/env bash

echo ${DOTFILE_SOURCE}


for dotfile in .vimrc .viminfo .vim; do
    if [[ -e "${HOME}/${dotfile}" ]]; then
        mv "${HOME}/${dotfile}" "${DOTFILE_BACKUP}"
    fi
done

ln -sfv "$(__dir__)" "${HOME}"/.vim
chmod 755 "${HOME}"/.vim
chmod 700 "${HOME}"/.vim/trace

# install vim-plug
curl -fLo "${HOME}"/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qa
