# preamble
brew "mas"

# terminal
brew "bash"
brew "bash-completion@2"
brew "tmux"
brew "vim"
cask "alacritty"

# fonts
tap "homebrew/cask-fonts"
cask "font-plemol-jp"
cask "font-plemol-jp-nf"

# general
brew "curl"
brew "fzf"
brew "ghq"
brew "git"
brew "git-lfs"
brew "jq"
brew "nkf"
brew "openssl"
brew "mise"
brew "tree"
brew "watch"
brew "wdiff"
brew "wget"
brew "yq"

# modern alternative
brew "bat"
brew "fd"
brew "httpie"
brew "ripgrep"

# gnu tools
brew "coreutils"
brew "diffutils"
brew "ed"
brew "findutils"
brew "gawk"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "gzip"
brew "make"

# platform tools
brew "aws-sam-cli"
brew "awscli"
brew "gh"
brew "packer"
brew "terraform"
cask "google-cloud-sdk"

# container tools
brew "helm"
brew "kind"
brew "kubectl"
brew "kubectx"
brew "kustomize"
brew "minikube"
brew "stern"
brew "velero"
cask "docker"

# databases
brew "postgresql"
brew "mysql"
brew "redis"

# linter, formatter
brew "actionlint"
brew "cfn-lint"
brew "jsonlint"
brew "shellcheck"
brew "shfmt"
brew "yamllint"

# desktop
cask "alfred"
cask "google-chrome"
cask "notion"
cask "slack"
