#!/usr/bin/env bash

function xdg_config_home() {
    echo "${HOME}"/.config
}

function load_brew() {
    if ! command -v brew &> /dev/null; then
        export PATH="/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/bin"
    fi
    if command -v brew &> /dev/null; then
        eval "$(brew shellenv)"
    fi
}
