#!/usr/bin/env bash

function __dir__() {
    echo $(cd -- "$(dirname -- "${BASH_SOURCE[1]}")" &> /dev/null && pwd)
}

function ghcd() {
    if [[ -z "${1}" ]]; then
        local opt_query=""
    else
        local opt_query="--query ${1}"
    fi
    cd "$(ghq root)/$(ghq list | fzf ${opt_query})"
}

function ghopen() {
    if [[ -z "${1}" ]]; then
        local opt_query=""
    else
        local opt_query="--query ${1}"
    fi
    gh repo view "$(ghq list | fzf ${opt_query})" --web
}
